### ISSUE TITLE
De datastorelinker gebruikt ergens in de code een postgres class (dit geeft problemen op een oracle omgeving)

### ISSUE THREAD

**Issue by mvdstruijk** [B3Partners/datastorelinker#117]
- Workaround: postgressql jar toevoegen in de tomcat/lib
- Fix: Code aanpassen zodat dit niet direct uit een postgres class gebruikt wordt
10-Jul-2020 14:34:32.777 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [StripesFilter]
	java.lang.NoClassDefFoundError: org/postgresql/largeobject/LargeObject
		at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
		at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
		at net.sourceforge.stripes.controller.AnnotatedClassActionResolver.processMethods(AnnotatedClassActionResolver.java:240)
		at net.sourceforge.stripes.controller.AnnotatedClassActionResolver.addActionBean(AnnotatedClassActionResolver.java:163)
		at net.sourceforge.stripes.controller.AnnotatedClassActionResolver.init(AnnotatedClassActionResolver.java:113)
		at net.sourceforge.stripes.controller.NameBasedActionResolver.init(NameBasedActionResolver.java:126)
		at net.sourceforge.stripes.config.DefaultConfiguration.init(DefaultConfiguration.java:146)
		at net.sourceforge.stripes.config.RuntimeConfiguration.init(RuntimeConfiguration.java:291)
		at net.sourceforge.stripes.controller.StripesFilter.createConfiguration(StripesFilter.java:137)
		at net.sourceforge.stripes.controller.StripesFilter.init(StripesFilter.java:103)
		at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4615)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1414)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1378)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1613)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:314)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1170)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1364)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: java.lang.ClassNotFoundException: org.postgresql.largeobject.LargeObject
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
		... 27 more

**Comment by mprins** [comment]
deze: https://github.com/B3Partners/datastorelinker/blob/df0ef0a639af6c273cc07c2ca60684c52ac67511/datastorelinker/src/main/java/nl/b3p/datastorelinker/gui/stripes/ConvertLargeObjectsAction.java#L26-L27

gebruikt op een paar plaatsen `org.postgresql.largeobject.LargeObject` en `org.postgresql.largeobject.LargeObjectManager`
maar er zit meer PG specifieke code in, bijv. https://github.com/B3Partners/datastorelinker/blob/df0ef0a639af6c273cc07c2ca60684c52ac67511/datastorelinker/src/main/java/nl/b3p/datastorelinker/gui/stripes/ConvertLargeObjectsAction.java#L92

dat is dus een Action die ook niet werkt op Oracle...
